"""Turn published agent trajectories into Trajectory objects we can re-score.

Public trajectory datasets ship the full conversation but no token accounting.
That is fine, and arguably better: prefix-cache behaviour is deterministic given
an append-only transcript, so we tokenize and simulate it ourselves rather than
trusting whatever the provider happened to report.

Schema handled (nvidia/Open-SWE-Traces):
    trajectory: list[{role, content, reasoning_content, think, tool_calls}]
    tools:      list[str]   -- JSON tool schemas, part of every request
    resolved:   int32
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Iterable, Sequence

from loopengg.costmodel import Trajectory, Turn

# Tools whose output is bulk text an agent must wade through. These are the
# compression targets; edits and control-flow calls are not.
READ_LIKE_TOOLS = {
    "execute_bash",
    "bash",
    "run",
    "str_replace_editor",
    "view",
    "read",
    "search",
    "grep",
    "find",
    "glob",
    "execute_ipython_cell",
    "browser",
}

EDIT_LIKE_TOOLS = {"str_replace", "create", "insert", "edit", "write", "apply_patch"}


class Tokenizer:
    """tiktoken if available, character heuristic otherwise.

    The datasets were produced by Qwen/Minimax models whose tokenizers differ
    from tiktoken's by roughly 10-20%. That is acceptable here because every
    claim is a *ratio* computed over the same trajectory with the same
    tokenizer, so the discrepancy cancels. Report the choice in the paper.
    """

    def __init__(self, encoding: str = "o200k_base") -> None:
        self.name = encoding
        self._enc = None
        try:
            import tiktoken

            self._enc = tiktoken.get_encoding(encoding)
        except Exception:
            self.name = "chars/4"

    def count(self, text: str | None) -> int:
        if not text:
            return 0
        if self._enc is not None:
            return len(self._enc.encode(text, disallowed_special=()))
        return max(1, len(text) // 4)


def _tool_call_tokens(tool_calls: Any, tok: Tokenizer) -> int:
    """Tool-call arguments are generated by the model, so they are output."""
    if not tool_calls:
        return 0
    total = 0
    for call in tool_calls:
        if not isinstance(call, dict):
            continue
        fn = call.get("function") or {}
        total += tok.count(fn.get("name", ""))
        total += tok.count(fn.get("arguments", ""))
    return total


def _tool_call_names(tool_calls: Any) -> list[str]:
    if not tool_calls:
        return []
    names = []
    for call in tool_calls:
        if isinstance(call, dict):
            fn = call.get("function") or {}
            if fn.get("name"):
                names.append(fn["name"])
    return names


def classify_turn(tool_names: Sequence[str], observation_tokens: int, min_obs: int) -> tuple[str, bool]:
    """Label a turn and decide whether its observation is worth delegating.

    An observation is delegatable when it is bulk output from a read-like tool
    and large enough that compressing it actually buys something. Small
    observations are left alone: compressing a 40-token result costs more than
    it saves.
    """
    if not tool_names:
        return "no_tool", False
    name = tool_names[0]
    base = name.split("__")[-1].lower()

    if any(e in base for e in EDIT_LIKE_TOOLS):
        return "edit", False
    if base in {"finish", "submit", "stop"}:
        return "terminate", False
    if any(r in base for r in READ_LIKE_TOOLS) or base in READ_LIKE_TOOLS:
        return ("read_exec", observation_tokens >= min_obs)
    return (base or "other", observation_tokens >= min_obs)


@dataclass
class IngestStats:
    n_messages: int = 0
    n_assistant: int = 0
    skipped_reason: str = ""


def messages_to_trajectory(
    messages: Sequence[dict],
    tools: Iterable[str] | None,
    tok: Tokenizer,
    *,
    task_id: str = "",
    min_delegatable_obs: int = 1000,
) -> tuple[Trajectory | None, IngestStats]:
    """Reconstruct per-turn context growth from a flat message list.

    Context at turn t is everything sent before the t-th assistant message,
    including the tool schemas, which are re-sent every request and are not
    negligible (OpenHands ships ~4 sizeable JSON schemas).
    """
    stats = IngestStats(n_messages=len(messages))
    if not messages:
        stats.skipped_reason = "empty"
        return None, stats

    schema_tokens = sum(tok.count(t) for t in (tools or []))

    # Walk the conversation, accumulating a running context and emitting one
    # Turn per assistant message.
    turns: list[Turn] = []
    running = schema_tokens
    pending_ctx: int | None = None
    pending_out = 0
    pending_types: list[str] = []
    pending_obs = 0

    def flush() -> None:
        nonlocal pending_ctx, pending_out, pending_types, pending_obs
        if pending_ctx is None:
            return
        ttype, delegatable = classify_turn(pending_types, pending_obs, min_delegatable_obs)
        turns.append(
            Turn(
                context_tokens=pending_ctx,
                output_tokens=pending_out,
                observation_tokens=pending_obs,
                turn_type=ttype,
                delegatable=delegatable,
            )
        )
        pending_ctx = None
        pending_out = 0
        pending_types = []
        pending_obs = 0

    for msg in messages:
        if not isinstance(msg, dict):
            continue
        role = msg.get("role", "")
        content_tokens = tok.count(msg.get("content"))

        if role == "assistant":
            flush()
            pending_ctx = running
            reasoning = tok.count(msg.get("reasoning_content"))
            calls = _tool_call_tokens(msg.get("tool_calls"), tok)
            pending_out = content_tokens + reasoning + calls
            pending_types = _tool_call_names(msg.get("tool_calls"))
            # Reasoning tokens are billed as output but are usually NOT carried
            # forward into the next request, so they do not grow the context.
            running += content_tokens + calls
        elif role == "tool":
            if pending_ctx is not None:
                pending_obs += content_tokens
            running += content_tokens
        else:  # system, user
            running += content_tokens

    flush()

    stats.n_assistant = len(turns)
    if not turns:
        stats.skipped_reason = "no assistant turns"
        return None, stats

    return Trajectory(turns=turns, task_id=task_id), stats


def load_shard(
    repo: str,
    filename: str,
    cache_dir: str = "data/hf_cache",
    limit: int | None = None,
) -> list[dict]:
    """Fetch one parquet shard and return its rows."""
    import pyarrow.parquet as pq
    from huggingface_hub import hf_hub_download

    path = hf_hub_download(repo, filename, repo_type="dataset", cache_dir=cache_dir)
    pf = pq.ParquetFile(path)
    rows: list[dict] = []
    for batch in pf.iter_batches(batch_size=64):
        rows.extend(batch.to_pylist())
        if limit is not None and len(rows) >= limit:
            return rows[:limit]
    return rows


def row_to_trajectory(
    row: dict, tok: Tokenizer, min_delegatable_obs: int = 1000
) -> tuple[Trajectory | None, IngestStats]:
    traj = row.get("trajectory")
    if isinstance(traj, str):
        try:
            traj = json.loads(traj)
        except json.JSONDecodeError:
            return None, IngestStats(skipped_reason="unparseable trajectory")
    return messages_to_trajectory(
        traj or [],
        row.get("tools"),
        tok,
        task_id=row.get("instance_id", ""),
        min_delegatable_obs=min_delegatable_obs,
    )
