"""Emit LaTeX tables from data/results.json so the paper never drifts from the data.

Writes figures/tables.tex, which main.tex can \\input directly.
"""

from __future__ import annotations

import json
from pathlib import Path

res = json.loads(Path("data/results.json").read_text())
cells = res["cells"]
out: list[str] = []

out.append("% AUTO-GENERATED by analysis/make_tables.py -- do not edit by hand\n")

# ---- Table 1: corpus shape + inflation -----------------------------------
out.append(r"""
\begin{tabular}{@{}lrrrr@{}}
\toprule
\textbf{Model / scaffold} & \textbf{Median} & \textbf{Median obs.} & \textbf{Cache hit} & \textbf{Flat} \\
 & \textbf{turns} & \textbf{(tokens)} & \textbf{rate} & \textbf{inflation} \\
\midrule""")
for c in cells:
    out.append(
        f"{c['label']} & {c['turns']['median']} & {c['observation_tokens']['p50']:,} & "
        f"{100 * c['inflation']['cache_hit_rate']:.1f}\\% & "
        f"\\textbf{{{c['inflation']['aggregate']:.2f}$\\times$}} \\\\"
    )
agg_hit = sum(c["inflation"]["cache_hit_rate"] for c in cells) / len(cells)
agg_inf = sum(c["inflation"]["aggregate"] for c in cells) / len(cells)
out.append(r"\midrule")
out.append(f"\\emph{{mean}} & --- & --- & {100 * agg_hit:.1f}\\% & "
           f"\\textbf{{{agg_inf:.2f}$\\times$}} \\\\")
out.append(r"\bottomrule" + "\n" + r"\end{tabular}")

# ---- Table 2: observation size distribution ------------------------------
out.append("\n\n% --- observation size distribution ---\n")
out.append(r"""\begin{tabular}{@{}lrrrrrr@{}}
\toprule
\textbf{Model / scaffold} & \textbf{p50} & \textbf{p75} & \textbf{p90} & \textbf{p95} & \textbf{p99} & \textbf{max} \\
\midrule""")
for c in cells:
    o = c["observation_tokens"]
    out.append(
        f"{c['label']} & {o['p50']:,} & {o['p75']:,} & {o['p90']:,} & "
        f"{o['p95']:,} & {o['p99']:,} & {o['p100']:,} \\\\"
    )
out.append(r"\bottomrule" + "\n" + r"\end{tabular}")

# ---- Table 3: saving vs threshold ---------------------------------------
out.append("\n\n% --- saving vs threshold (R1 / B3) ---\n")
thresholds = [r["threshold"] for r in cells[0]["threshold_sweep"]]
out.append(r"\begin{tabular}{@{}l" + "r" * len(thresholds) + r"@{}}")
out.append(r"\toprule")
out.append(r"\textbf{Model / scaffold} & " +
           " & ".join(f"\\textbf{{{t}}}" for t in thresholds) + r" \\")
out.append(r"\midrule")
for c in cells:
    row = []
    for r in c["threshold_sweep"]:
        r1, b3 = r["R1_saving_pct"], r["B3_saving_pct"]
        mark = "" if r1 >= b3 else ""
        row.append(f"{r1:.1f} / \\textbf{{{b3:.1f}}}{mark}")
    out.append(f"{c['label']} & " + " & ".join(row) + r" \\")
out.append(r"\bottomrule" + "\n" + r"\end{tabular}")

# ---- Table 4: ceiling + growth decomposition ----------------------------
out.append("\n\n% --- ceiling and growth decomposition ---\n")
out.append(r"""\begin{tabular}{@{}lrrr@{}}
\toprule
\textbf{Model / scaffold} & \textbf{Obs. \% of growth} & \textbf{Output \% of growth} & \textbf{Ceiling} \\
\midrule""")
for c in cells:
    g = c["growth"]
    out.append(
        f"{c['label']} & {100 * g['obs_share']:.1f}\\% & "
        f"{100 * (1 - g['obs_share']):.1f}\\% & "
        f"{c['ceiling']['saving_pct']:.1f}\\% \\\\"
    )
out.append(r"\bottomrule" + "\n" + r"\end{tabular}")

Path("figures").mkdir(exist_ok=True)
Path("figures/tables.tex").write_text("\n".join(out), encoding="utf-8")
print("wrote figures/tables.tex")

# Also print a plain summary for the working doc.
print("\n=== SUMMARY ===")
for c in cells:
    sw = c["threshold_sweep"]
    neg = [r["threshold"] for r in sw if r["R1_saving_pct"] < 0]
    beats = sum(1 for r in sw if r["B3_saving_pct"] >= r["R1_saving_pct"])
    print(f"{c['label']:22} infl={c['inflation']['aggregate']:.2f}x  "
          f"hit={100 * c['inflation']['cache_hit_rate']:.1f}%  "
          f"p50obs={c['observation_tokens']['p50']:>4}  "
          f"ceiling={c['ceiling']['saving_pct']:.1f}%  "
          f"B3>=R1 at {beats}/{len(sw)} thresholds  "
          f"R1 negative at {neg if neg else 'none'}")
